### PR TITLE
fix url syntax

### PR DESCRIPTION
**Pull request by vendethiel**

### CODE REVIEW

**Comment by vendethiel** [comment]
Seems like github doesn't handle it, oh well.

[it's the correct syntax, tho](http://docutils.sourceforge.net/docs/user/rst/quickref.html#hyperlink-targets)

**Comment by refi64** [comment]
Oh, right! I knew about the rST syntax, but I've contributed to projects with Markdown README's several times before, and I always mix them up.

Also, could it be that there needs to be a space before the `<`? I usually put one.

**Comment by vendethiel** [comment]
Any reason to have this in rst instead of md, btw?

**Comment by refi64** [comment]
@vendethiel Not really. I generally like rST more.

**Comment by refi64** [comment]
Fixed.

**Comment by vendethiel** [comment]
Cool :D. Btw man, always like to see you on weird languages, it's fun

**Pull request closed without merging**
